// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammingPractice_L19.Database;

#nullable disable

namespace ProgrammingPractice_L19.Migrations
{
    [DbContext(typeof(FishFirmDbContext))]
    partial class FishFirmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ConstructionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Displacement")
                        .HasColumnType("double");

                    b.Property<bool>("IsBusy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.FishGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("JarId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("VoyageId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("JarId", "VoyageId", "PeriodId");

                    b.ToTable("FishGroups");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Fisherman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Fishermen");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Jar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Jars");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "root",
                            Password = "12345",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Login = "pop",
                            Password = "12345",
                            Role = "manager"
                        });
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Voyage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BoatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VoyageNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.ToTable("Voyages");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.VoyageFisherman", b =>
                {
                    b.Property<int>("FishermanId")
                        .HasColumnType("int");

                    b.Property<int>("VoyageId")
                        .HasColumnType("int");

                    b.HasKey("FishermanId", "VoyageId");

                    b.HasIndex("VoyageId");

                    b.ToTable("VoyageFisherman");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.VoyageJar", b =>
                {
                    b.Property<int>("JarId")
                        .HasColumnType("int");

                    b.Property<int>("VoyageId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BoatArrive")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BoatSillAway")
                        .HasColumnType("datetime(6)");

                    b.HasKey("JarId", "VoyageId", "PeriodId");

                    b.HasIndex("VoyageId");

                    b.ToTable("VoyageJar");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.FishGroup", b =>
                {
                    b.HasOne("ProgrammingPractice_L19.Model.VoyageJar", "VoyageJar")
                        .WithMany("Fishes")
                        .HasForeignKey("JarId", "VoyageId", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoyageJar");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Voyage", b =>
                {
                    b.HasOne("ProgrammingPractice_L19.Model.Boat", "CurrentBoat")
                        .WithMany()
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentBoat");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.VoyageFisherman", b =>
                {
                    b.HasOne("ProgrammingPractice_L19.Model.Fisherman", "Fisherman")
                        .WithMany("Voyages")
                        .HasForeignKey("FishermanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgrammingPractice_L19.Model.Voyage", "Voyage")
                        .WithMany("Fishermen")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fisherman");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.VoyageJar", b =>
                {
                    b.HasOne("ProgrammingPractice_L19.Model.Jar", "Jar")
                        .WithMany("Voyages")
                        .HasForeignKey("JarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgrammingPractice_L19.Model.Voyage", "Voyage")
                        .WithMany("Jars")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jar");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Fisherman", b =>
                {
                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Jar", b =>
                {
                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.Voyage", b =>
                {
                    b.Navigation("Fishermen");

                    b.Navigation("Jars");
                });

            modelBuilder.Entity("ProgrammingPractice_L19.Model.VoyageJar", b =>
                {
                    b.Navigation("Fishes");
                });
#pragma warning restore 612, 618
        }
    }
}
